spring:
   datasource:
      url:  jdbc:postgresql://localhost:5432/sdgfhir
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
   jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: target/lucenefiles
      hibernate.search.lucene_version: LUCENE_CURRENT
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
hapi:
  fhir:
    version: dstu3
    server:
      path: /fhir/*
    rest:
      server-name: hapi-fhir-spring-boot-sample-server-jpa
      server-version: 1.0.0
      implementation-description: Spring Boot Jpa Server Sample
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: true
      request-only: true
    jpa:
      scheduling-disabled: true
      subscription-enabled: false
      auto-create-placeholder-reference-targets: true
management:
  security:
    enabled: false
#   fhirDaoConfig.setAutoCreatePlaceholderReferenceTargets(true);
